/** Catalog prefixes the server scrapes, in priority order: the major first, then departments the degree requires, then common LSU gen-ed departments. */
export const CATALOG_SCRAPE_DEPARTMENTS = [
  "CSC",
  "MATH",
  "ENGL",
  "PHYS",
  "CHEM",
  "BIOL",
  "EE",
  "IE",
  "EXST",
  "GEOL",
  "ASTR",
  "HIST",
  "ECON",
  "PSYC",
  "SOCL",
  "POLI",
  "PHIL",
  "CMST",
  "GEOG",
  "ANTH",
  "ART",
  "MUS",
  "THTR",
  "SPAN",
  "FREN",
] as const;
